#!/bin/bash 

echo "TESTING: ArrayTest/Main.jack"
python3 /Users/satej/Documents/workspace/classwork/compsys/n2trepo/project10/src/parser.py /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/ArrayTest/Main.jack && xmllint --format /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/ArrayTest/Main.xml | tail -n +2 | sed -e $'s:<expressionList>  </expressionList>:<expressionList>\\\n</expressionList>:g' -e $'s:<parameterList>  </parameterList>:<parameterList>\\\n</parameterList>:g' > /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/ArrayTest/Main.lint.xml
/Users/satej/Documents/workspace/classwork/compsys/nand2tetris/tools/TextComparer.sh /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/ArrayTest/Main.lint.xml /Users/satej/Documents/workspace/classwork/compsys/nand2tetris//projects/10/ArrayTest/Main.ref.xml


echo "TESTING: ExpressionLessSquare/Main.jack"
python3 /Users/satej/Documents/workspace/classwork/compsys/n2trepo/project10/src/parser.py /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/ExpressionLessSquare/Main.jack && xmllint --format /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/ExpressionLessSquare/Main.xml | tail -n +2 | sed -e $'s:<expressionList>  </expressionList>:<expressionList>\\\n</expressionList>:g' -e $'s:<parameterList>  </parameterList>:<parameterList>\\\n</parameterList>:g' > /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/ExpressionLessSquare/Main.lint.xml
/Users/satej/Documents/workspace/classwork/compsys/nand2tetris/tools/TextComparer.sh /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/ExpressionLessSquare/Main.lint.xml /Users/satej/Documents/workspace/classwork/compsys/nand2tetris//projects/10/ExpressionLessSquare/Main.ref.xml

echo "TESTING: ExpressionLessSquare/Square.jack"
python3 /Users/satej/Documents/workspace/classwork/compsys/n2trepo/project10/src/parser.py /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/ExpressionLessSquare/Square.jack && xmllint --format /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/ExpressionLessSquare/Square.xml | tail -n +2 | sed -e $'s:<expressionList>  </expressionList>:<expressionList>\\\n</expressionList>:g' -e $'s:<parameterList>  </parameterList>:<parameterList>\\\n</parameterList>:g' > /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/ExpressionLessSquare/Square.lint.xml
/Users/satej/Documents/workspace/classwork/compsys/nand2tetris/tools/TextComparer.sh /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/ExpressionLessSquare/Square.lint.xml /Users/satej/Documents/workspace/classwork/compsys/nand2tetris//projects/10/ExpressionLessSquare/Square.ref.xml

echo "TESTING: ExpressionLessSquare/SquareGame.jack"
python3 /Users/satej/Documents/workspace/classwork/compsys/n2trepo/project10/src/parser.py /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/ExpressionLessSquare/SquareGame.jack && xmllint --format /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/ExpressionLessSquare/SquareGame.xml | tail -n +2 | sed -e $'s:<expressionList>  </expressionList>:<expressionList>\\\n</expressionList>:g' -e $'s:<parameterList>  </parameterList>:<parameterList>\\\n</parameterList>:g' > /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/ExpressionLessSquare/SquareGame.lint.xml
/Users/satej/Documents/workspace/classwork/compsys/nand2tetris/tools/TextComparer.sh /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/ExpressionLessSquare/SquareGame.lint.xml /Users/satej/Documents/workspace/classwork/compsys/nand2tetris//projects/10/ExpressionLessSquare/SquareGame.ref.xml


echo "TESTING: Square/Main.jack"
python3 /Users/satej/Documents/workspace/classwork/compsys/n2trepo/project10/src/parser.py /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/Square/Main.jack && xmllint --format /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/Square/Main.xml | tail -n +2 | sed -e $'s:<expressionList>  </expressionList>:<expressionList>\\\n</expressionList>:g' -e $'s:<parameterList>  </parameterList>:<parameterList>\\\n</parameterList>:g' > /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/Square/Main.lint.xml
/Users/satej/Documents/workspace/classwork/compsys/nand2tetris/tools/TextComparer.sh /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/Square/Main.lint.xml /Users/satej/Documents/workspace/classwork/compsys/nand2tetris//projects/10/Square/Main.ref.xml

echo "TESTING: Square/Square.jack"
python3 /Users/satej/Documents/workspace/classwork/compsys/n2trepo/project10/src/parser.py /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/Square/Square.jack && xmllint --format /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/Square/Square.xml | tail -n +2 | sed -e $'s:<expressionList>  </expressionList>:<expressionList>\\\n</expressionList>:g' -e $'s:<parameterList>  </parameterList>:<parameterList>\\\n</parameterList>:g' > /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/Square/Square.lint.xml
/Users/satej/Documents/workspace/classwork/compsys/nand2tetris/tools/TextComparer.sh /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/Square/Square.lint.xml /Users/satej/Documents/workspace/classwork/compsys/nand2tetris//projects/10/Square/Square.ref.xml

echo "TESTING: Square/SquareGame.jack"
python3 /Users/satej/Documents/workspace/classwork/compsys/n2trepo/project10/src/parser.py /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/Square/SquareGame.jack && xmllint --format /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/Square/SquareGame.xml | tail -n +2 | sed -e $'s:<expressionList>  </expressionList>:<expressionList>\\\n</expressionList>:g' -e $'s:<parameterList>  </parameterList>:<parameterList>\\\n</parameterList>:g' > /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/Square/SquareGame.lint.xml
/Users/satej/Documents/workspace/classwork/compsys/nand2tetris/tools/TextComparer.sh /Users/satej/Documents/workspace/classwork/compsys/nand2tetris/projects/10/Square/SquareGame.lint.xml /Users/satej/Documents/workspace/classwork/compsys/nand2tetris//projects/10/Square/SquareGame.ref.xml